### ISSUE TITLE
.vertical @startColor not found

### ISSUE THREAD

**Issue by clearly** [ExactTarget/fuelux#1158]
Constantly keep getting this on a vanilla bower install.
  LESS Syntax error : Named argument for .vertical @startColor not found
  LESS File : /root/project/client/vendor/fuelux/less/repeater-list.less 112:5
Error: Named argument for .vertical @startColor not found

**Comment by interactivellama** [comment]
This is working for us.

Here is an example of parametric mixins from the [Less documentation](http://lesscss.org/features/#mixins-parametric-feature)

```
.border-radius(@radius: 5px) {
  -webkit-border-radius: @radius;
     -moz-border-radius: @radius;
          border-radius: @radius;
}
```

**Comment by minddust** [comment]
for those who stuck at the same error - mine was produced by a name collision with the bootstrap version of `.vertical`. bootstrap has a slightly different naming with their parameters (**with dash**) and this causes the error where the less compiler can't find the right named parameter. code below:

**bootstrap**
```less

#gradient {

  .vertical(@start-color: #555; @end-color: #333; @start-percent: 0%; @end-percent: 100%) {
    background-image: -webkit-linear-gradient(top, @start-color @start-percent, @end-color @end-percent); // Safari 5.1-6, Chrome 10+
    background-image: -o-linear-gradient(top, @start-color @start-percent, @end-color @end-percent); // Opera 12
    background-image: linear-gradient(to bottom, @start-color @start-percent, @end-color @end-percent); // Standard, IE10, Firefox 16+, Opera 12.10+, Safari 7+, Chrome 26+
    background-repeat: repeat-x;
    filter: e(%("progid:DXImageTransform.Microsoft.gradient(startColorstr='%d', endColorstr='%d', GradientType=0)",argb(@start-color), argb(@end-color))); // IE9 and down
  }
}
```

**fuelux**
```less
#gradient {
	.vertical(@startColor: #555, @endColor: #333) {
		background-color: mix(@startColor, @endColor, 60%);
		background-image: -moz-linear-gradient(top, @startColor, @endColor); // FF 3.6+
		background-image: -webkit-gradient(linear, 0 0, 0 100%, from(@startColor), to(@endColor)); // Safari 4+, Chrome 2+
		background-image: -webkit-linear-gradient(top, @startColor, @endColor); // Safari 5.1+, Chrome 10+
		background-image: -o-linear-gradient(top, @startColor, @endColor); // Opera 11.10
		background-image: linear-gradient(to bottom, @startColor, @endColor); // Standard, IE10
		background-repeat: repeat-x;
		filter: e(%("progid:DXImageTransform.Microsoft.gradient(startColorstr='%d', endColorstr='%d', GradientType=0)",argb(@startColor),argb(@endColor))); // IE9 and down
	}
}
```
